version: "2"
linters:
  enable:
    - decorder
    - dogsled
    - dupword
    - err113
    - exhaustive
    - exhaustruct
    - forbidigo
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gosec
    - ireturn
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - revive
  settings:
    errcheck:
      disable-default-exclusions: true
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - io/ioutil.ReadFile
        - io.Copy(*bytes.Buffer)
        - io.Copy(os.Stdout)
    exhaustruct:
      include:
        - .+\.Test
        - example\.com/package\.ExampleStruct[\d]{1,2}
      exclude:
        - .+/cobra\.Command$
    forbidigo:
      forbid:
        - pattern: ^print(ln)?$
        - pattern: ^spew\.(ConfigState\.)?Dump$
        - pattern: ^v1.Dump$
          pkg: ^example.com/pkg/api/v1$
      exclude-godoc-examples: false
      analyze-types: true
    gocognit:
      min-complexity: 20
    goconst:
      match-constant: false
      min-len: 3
      min-occurrences: 3
      numbers: false
      min: 2
      max: 2
      ignore-calls: false
      ignore-strings: foo.+
    gocyclo:
      min-complexity: 20
    ireturn:
      allow:
        - anon
        - (or|er)$
      reject:
        - github.com\/user\/package\/v4\.Type
    nestif:
      min-complexity: 4
    nilnil:
      detect-opposite: true
      checked-types:
        - chan
        - func
        - iface
        - map
        - ptr
        - uintptr
        - unsafeptr
    nlreturn:
      block-size: 2
    wsl:
      strict-append: false
      allow-assign-and-call: false
      allow-assign-and-anything: true
      allow-multiline-assign: false
      force-case-trailing-whitespace: 1
      allow-trailing-comment: true
      allow-separated-leading-comment: true
      allow-cuddle-declarations: true
      allow-cuddle-with-calls:
        - Foo
        - Bar
      allow-cuddle-with-rhs:
        - Foo
        - Bar
      force-err-cuddling: true
      error-variable-names:
        - foo
      force-short-decl-cuddling: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - goconst
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
