version: "2"
linters:
  enable:
  # - containedctx
  # - contextcheck
  - copyloopvar
  - cyclop
  - decorder
  - dupl
  - dupword
  - err113
  - errcheck
  - errname
  - errorlint
  - exhaustive
  - exptostd
  - fatcontext
  - forbidigo
  - forcetypeassert
  - funcorder
  - funlen
  - gocheckcompilerdirectives
  - gocognit
  - goconst
  - gocritic
  - godox
  - gosec
  - govet
  - iface
  - inamedparam
  - ineffassign
  - intrange
  - ireturn
  - loggercheck
  - maintidx
  - modernize
  - musttag
  - nestif
  - nilerr
  - nilnil
  - nlreturn
  - nonamedreturns
  - perfsprint
  - revive
  - staticcheck
  - testifylint
  - thelper
  - unconvert
  - unparam
  - unused
  - usestdlibvars
  - wastedassign
  - wrapcheck
  settings:
    errcheck:
      disable-default-exclusions: true
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - io/ioutil.ReadFile
        - io.Copy(*bytes.Buffer)
        - io.Copy(os.Stdout)
    forbidigo:
      forbid:
        - pattern: ^print(ln)?$
        - pattern: ^spew\.(ConfigState\.)?Dump$
        - pattern: ^v1.Dump$
          pkg: ^example.com/pkg/api/v1$
      exclude-godoc-examples: false
      analyze-types: true
    funcorder:
      # Checks that constructors are placed after the structure declaration.
      # Default: true
      constructor: true
      # Checks if the exported methods of a structure are placed before the non-exported ones.
      # Default: true
      struct-method: false
      # Checks if the constructors and/or structure methods are sorted alphabetically.
      # Default: false
      alphabetical: true
    gocognit:
      min-complexity: 15
    govet:
      enable-all: true
      disable:
        - fieldalignment
    ineffassign:
      check-escaping-errors: true
    ireturn:
      allow:
        - generic
        - error
        - stdlib
    nilnil:
      detect-opposite: true
    testifylint:
      enable-all: true
    unconvert:
      # Remove conversions that force intermediate rounding.
      # Default: false
      fast-math: true
      # Be more conservative (experimental)
      # Default: false
      safe: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - goconst
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$