name: Mirror to Codeberg

on: [push, delete]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      # actions/checkout@v4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      # pixta-dev/repository-mirroring-action@v1.1.1
      - uses: pixta-dev/repository-mirroring-action@4125b0450505193910c571761899984920239634
        with:
          target_repo_url: git@codeberg.org:richbl/go-ble-sync-cycle.git
          ssh_private_key: ${{ secrets.CODEBERG_SSH_KEY }}
